name: pocketbase_mobile_flutter
version: 1.0.2+2
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.1 <4.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.8
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.2.1
  flutter_inappwebview: ^6.0.0
  upgrader: ^10.3.0
  contactus: ^1.2.3
  share_plus: ^9.0.0
  url_launcher: ^6.3.0
  pocketbase_server_flutter: ^0.0.1

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  package_rename: ^1.7.0
  flutter_test: 
    sdk: flutter

get_cli: 
  sub_folder: false

# dart run package_rename
package_rename_config:
  android:
    app_name: "Pocketbase Mobile"
    package_name: "com.pocketbase.mobile"

  ios:
    app_name: "Pocketbase Mobile"
    bundle_name: "com.pocketbase.mobile"
    package_name: "com.pocketbase.mobile"

flutter_launcher_icons: 
  android: launcher_icon
  image_path: assets/icon.jpg
  ios: true

flutter: 
  assets: 
    - assets/
  uses-material-design: true

