name: pocketbase_mobile_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.1 <4.0.0'

dependencies:  
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

get_cli: 
  sub_folder: false

flutter: 
  uses-material-design: true

