name: pocketbase_mobile_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.1 <4.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  flex_color_scheme: ^7.1.2
  google_fonts: ^4.0.5
  flutter_inappwebview: ^6.0.0-beta.22
  flutter_advanced_drawer: ^1.3.5
  upgrader: ^6.3.0
  contactus: ^1.2.0
  input_history_text_field: ^0.2.0
  share_plus: ^4.4.0
  url_launcher: ^6.1.10

dependency_overrides: 
  http: ^0.13.5

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  package_rename: ^1.3.0
  flutter_test: 
    sdk: flutter

get_cli: 
  sub_folder: false

# dart run package_rename
package_rename_config:
  android:
    app_name: "Pocketbase Mobile"
    package_name: "com.pocketbase.mobile"

  ios:
    app_name: "Pocketbase Mobile"
    bundle_name: "com.pocketbase.mobile"
    package_name: "com.pocketbase.mobile"

flutter_launcher_icons: 
  android: launcher_icon
  image_path: assets/icon.jpg
  ios: true

flutter: 
  assets: 
    - assets/
  uses-material-design: true

