import 'package:flutter/material.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:pocketbase_mobile_flutter/app/data/app_data.dart';
import 'package:share_plus/share_plus.dart';
import 'package:url_launcher/url_launcher.dart';

class AdminPanelView extends StatelessWidget {
  final String adminPanelUrl;
  const AdminPanelView({super.key, required this.adminPanelUrl});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Theme.of(context).colorScheme.tertiary,
      appBar: AppBar(
        title: const Text('Pocketbase Mobile'),
        centerTitle: true,
        actions: [
          IconButton(
            onPressed: () {
              launchUrl(
                Uri.parse(adminPanelUrl),
                mode: LaunchMode.externalApplication,
              );
            },
            icon: const Icon(Icons.open_in_browser),
          ),
          IconButton(
            onPressed: () {
              String shareMessage =
                  "Pocketbase admin url: $adminPanelUrl\n\n Generated by Pocketbase Mobile app. ${AppUtils.pocketbaseUrl}";
              Share.share(shareMessage);
            },
            icon: const Icon(Icons.share),
          ),
        ],
      ),
      body: InAppWebView(
        initialUrlRequest: URLRequest(url: WebUri(adminPanelUrl)),
        initialSettings: InAppWebViewSettings(
          javaScriptEnabled: true,
          cacheEnabled: true,
          preferredContentMode: UserPreferredContentMode.DESKTOP,
        ),
      ),
    );
  }
}
